FROM centos:6.7
MAINTAINER gavin@usemarkup.com
RUN yum clean all && \
yum install -y sudo openssh-server openssh-clients which curl \
htop initscripts net-tools wget cronie procps \
git glances vim dnsmasq screen bind-utils telnet ntp \
strace ncdu mlocate lynx fail2ban nc logrotate
